# @package _global_

defaults:
  - base_config
  - run: local
  - dataset: vqa
  - model: base_model
  - callbacks@_callback_dict.logging: logging
  - callbacks@_callback_dict.csv: csv
  - callbacks@_callback_dict.wandb: wandb
  - callbacks@_callback_dict.cost_logging: cost_logging
  - _self_

_callback_dict:
  csv:
    file_path: ${model.name}-outputs.csv
  wandb:
    project: visassistant

callbacks: ${oc.dict.values:_callback_dict}